name: goreleaser

on: [push, pull_request]

jobs:
  goreleaser:
    # name: Go Releaser
    env:
      GOPATH: ${{ github.workspace }}/go
      GO111MODULE: off
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: go/src/
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13'

      - run: go get -u -v github.com/golang/dep/cmd/dep

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v1

      - run: dep ensure

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
          key: ${{ secrets.YOUR_PRIVATE_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
