name: goreleaser

on: [push, pull_request]

jobs:
  goreleaser:
    # name: Go Releaser
    env:
      GOPATH: ${{ github.workspace }}/go
      GO111MODULE: off
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: go/src/github.com/${{ github.repository }}

      - run: git fetch --prune --unshallow
        working-directory: go/src/github.com/${{ github.repository }}

      - uses: actions/setup-go@v1
        with:
          go-version: '1.13'

      - run: go get -u -v github.com/golang/dep/cmd/dep
      # - run: sudo apt install go-dep

      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v1

      - run: $GOPATH/bin/dep ensure
        working-directory: go/src/github.com/${{ github.repository }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
          key: ${{ secrets.YOUR_PRIVATE_KEY }}
          workdir: ./go/src/github.com/${{ github.repository }}/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
