name: goreleaser

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  goreleaser:
    name: Go Releaser
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Get dependencies
        run: |
          # sudo apt install go-dep -y
          # mkdir -p $HOME/go/src/
          go get -u -v github.com/golang/dep/cmd/dep
          ln -s $PWD $HOME/go/src/
          cd $HOME/go/src/nickns
          $HOME/go/bin/dep ensure

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
          key: ${{ secrets.YOUR_PRIVATE_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
