name: goreleaser

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  goreleaser:
    name: Go Releaser
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Add dep
        run: go get -u -v github.com/golang/dep/cmd/dep

      - name: Create Symbolic Link
        run: ln -s $PWD $HOME/go/src/

      - name: Change Dir
        run: cd $HOME/go/src/nickns

      - name: Dep ensure
        run: $HOME/go/bin/dep ensure

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v1

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
          key: ${{ secrets.YOUR_PRIVATE_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
